// Database types - will be auto-generated by Supabase CLI
// For now, using placeholder types that match our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string
          avatar_url: string | null
          google_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name: string
          avatar_url?: string | null
          google_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          avatar_url?: string | null
          google_id?: string | null
          updated_at?: string
        }
      }
      workspaces: {
        Row: {
          id: string
          name: string
          slug: string
          google_domain: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          google_domain?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          slug?: string
          google_domain?: string | null
          updated_at?: string
        }
      }
      boards: {
        Row: {
          id: string
          workspace_id: string
          name: string
          description: string | null
          slug: string
          is_archived: boolean
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          name: string
          description?: string | null
          slug: string
          is_archived?: boolean
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          description?: string | null
          slug?: string
          is_archived?: boolean
          updated_at?: string
        }
      }
      columns: {
        Row: {
          id: string
          board_id: string
          name: string
          position: number
          wip_limit: number | null
          is_done_column: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          board_id: string
          name: string
          position: number
          wip_limit?: number | null
          is_done_column?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          position?: number
          wip_limit?: number | null
          is_done_column?: boolean
          updated_at?: string
        }
      }
      cards: {
        Row: {
          id: string
          board_id: string
          column_id: string
          title: string
          description: string | null
          position: number
          priority: 'low' | 'medium' | 'high' | 'critical' | null
          due_date: string | null
          time_estimate_minutes: number | null
          time_logged_minutes: number
          is_archived: boolean
          sync_to_google: boolean
          created_by: string
          created_at: string
          updated_at: string
          completed_at: string | null
        }
        Insert: {
          id?: string
          board_id: string
          column_id: string
          title: string
          description?: string | null
          position: number
          priority?: 'low' | 'medium' | 'high' | 'critical' | null
          due_date?: string | null
          time_estimate_minutes?: number | null
          time_logged_minutes?: number
          is_archived?: boolean
          sync_to_google?: boolean
          created_by: string
          created_at?: string
          updated_at?: string
          completed_at?: string | null
        }
        Update: {
          column_id?: string
          title?: string
          description?: string | null
          position?: number
          priority?: 'low' | 'medium' | 'high' | 'critical' | null
          due_date?: string | null
          time_estimate_minutes?: number | null
          time_logged_minutes?: number
          is_archived?: boolean
          sync_to_google?: boolean
          updated_at?: string
          completed_at?: string | null
        }
      }
      subtasks: {
        Row: {
          id: string
          card_id: string
          parent_subtask_id: string | null
          title: string
          is_completed: boolean
          assignee_id: string | null
          due_date: string | null
          position: number
          is_checklist_item: boolean
          created_at: string
          updated_at: string
          completed_at: string | null
        }
        Insert: {
          id?: string
          card_id: string
          parent_subtask_id?: string | null
          title: string
          is_completed?: boolean
          assignee_id?: string | null
          due_date?: string | null
          position: number
          is_checklist_item?: boolean
          created_at?: string
          updated_at?: string
          completed_at?: string | null
        }
        Update: {
          title?: string
          is_completed?: boolean
          assignee_id?: string | null
          due_date?: string | null
          position?: number
          is_checklist_item?: boolean
          updated_at?: string
          completed_at?: string | null
        }
      }
      labels: {
        Row: {
          id: string
          board_id: string
          name: string
          color: string
          created_at: string
        }
        Insert: {
          id?: string
          board_id: string
          name: string
          color: string
          created_at?: string
        }
        Update: {
          name?: string
          color?: string
        }
      }
      card_assignments: {
        Row: {
          id: string
          card_id: string
          user_id: string
          created_at: string
        }
        Insert: {
          id?: string
          card_id: string
          user_id: string
          created_at?: string
        }
        Update: never
      }
      card_labels: {
        Row: {
          id: string
          card_id: string
          label_id: string
          created_at: string
        }
        Insert: {
          id?: string
          card_id: string
          label_id: string
          created_at?: string
        }
        Update: never
      }
      board_members: {
        Row: {
          id: string
          board_id: string
          user_id: string
          role: 'viewer' | 'contributor' | 'admin'
          created_at: string
        }
        Insert: {
          id?: string
          board_id: string
          user_id: string
          role?: 'viewer' | 'contributor' | 'admin'
          created_at?: string
        }
        Update: {
          role?: 'viewer' | 'contributor' | 'admin'
        }
      }
      workspace_members: {
        Row: {
          id: string
          workspace_id: string
          user_id: string
          role: 'owner' | 'admin' | 'member'
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          user_id: string
          role?: 'owner' | 'admin' | 'member'
          created_at?: string
        }
        Update: {
          role?: 'owner' | 'admin' | 'member'
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']
